### PR TITLE
Fix issue #46

### LINKED ISSUE #46: Mismatching DokanOptions
When implementing `DokanFileSystem#zwCreateFile` one has two objects that wrap the same native DokanOptions-Object:
`DokanFileSystem#dokanOptions` written on mount
and `DokanFileInfo#DokanOpts` which is generated from the pointer every time the method is invoked.

Tests show that those two references do indeed point to the same native address, but are out of sync. From my perspective the native object is (wrongly!) changed after mount which results in differing values that shouldn't be different.
My tests with this code ([branch ](https://github.com/JaniruTEC/dokan-java/tree/issue-46)/ https://github.com/JaniruTEC/dokan-java/commit/8b636ca8c05052162127753bead7204ff765c754) yield the following results:
`This: DeviceOptions(Version=110, ThreadCount=5, Options=138, mountOptions=EnumIntegerSet(elements=[STD_ERR_OUTPUT, WRITE_PROTECTION, CURRENT_SESSION]), GlobalContext=0, MountPoint=M:, UNCName=null, Timeout=3000, AllocationUnitSize=4096, SectorSize=512)`

`Parameter: DeviceOptions(Version=110, ThreadCount=5, Options=138, mountOptions=EnumIntegerSet(elements=[STD_ERR_OUTPUT, WRITE_PROTECTION, CURRENT_SESSION]), GlobalContext=0, MountPoint=M:, UNCName=null, Timeout=2199023258552, AllocationUnitSize=512, SectorSize=512)`

It shows that only two fields are affected (Timeout and AllocationUnitSize). It seems that this error has it's origin in @dokan-dev/dokan-core. Maybe you guys know more.

### PR DESCRIPTION
**Pull request by JaniruTEC**
Added MAPPING.md as common guideline for type-conversions
Added new Annotation (Unsigned) used to indicate that an integer type or integer type pointer refers to an unsigned value.
Corrected types of fields in structures to match Dokany
Added Unsigned-Annotation to all accessors of unsigned values
Added UnsignedNumbers class with conversion methods between unsigned integer types and String

Merging this PR closes issue #46

### CODE REVIEW

File: src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java [hunk 1]
```diff
@@ -93,7 +94,7 @@ public int zwCreateFile(WString rawPath, DokanIOSecurityContext securityContext,
             }
         }
 
-        long val = this.handleHandler.incrementAndGet();
+        @Unsigned long val = this.handleHandler.incrementAndGet();
```
Comment (infeo) [inline src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java:97]: Here the annotation is actually not needed, since this is "just" an example filesystem implementation.

File: src/main/java/dev/dokan/dokan_java/structure/DokanControl.java [hunk 2]
```diff
@@ -19,12 +22,13 @@
...
      */
-    public long Type;
+    @Unsigned
+    public int Type;
 
     /**
      * Mount point. Can be "M:\" (drive letter) or "C:\mount\dokan" (path in NTFS)
      */
-    public char[] MountPoint = new char[256];
+    public char[] MountPoint = new char[WinNT.MAX_PATH];
```
Comment (infeo) [inline src/main/java/dev/dokan/dokan_java/structure/DokanControl.java:31]: Actually not part of this PR. But let's take it in.

File: src/main/java/dev/dokan/dokan_java/structure/DokanControl.java [hunk 3]
```diff
@@ -79,19 +83,28 @@ public DokanControl(Pointer p, long offset) {
...
+         * Let's do the math:
+         * A list that uses an unsigned int (32 bit) as index could save up to 2^32 objects.
+         * Even if it only saved one byte in each entry (not accounting for the actual overhead of the entries themselves),
+         * that would be 2^32 bytes = 4 GB for that list alone!
+         * If the list of active Dokan MountPoints exceeds 2^31 (signed int) entries, we probably have other problems.
+         *
+         * But let's assume that this could still happen:
+         * In this case we want the application to crash so that someone else can fix that nonsense.
+         * "assert" seems like a good choice for this case (for once).
+         */
```
Comment (infeo) [inline src/main/java/dev/dokan/dokan_java/structure/DokanControl.java]: As discussed: Less sassy, and move it the javadocs part for documentation purpose.

File: src/main/java/dev/dokan/dokan_java/UnsignedNumbers.java [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+    }
+
+    public static String toUnsignedString(@Unsigned int value) {
+        return Integer.toUnsignedString(value);
+    }
+
+    public static String toUnsignedString(@Unsigned long value) {
+        return Long.toUnsignedString(value);
+    }
+
```
Comment (infeo) [inline src/main/java/dev/dokan/dokan_java/UnsignedNumbers.java:25]: As discussed: It would be nice to have also delegate methods for unsigned division and other operations, which are different from their signed counterparts.

File: src/main/java/dev/dokan/dokan_java/Unsigned.java [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+
+import java.lang.annotation.Documented;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+import static java.lang.annotation.ElementType.*;
+
+
+@Documented
```
Comment (infeo) [inline src/main/java/dev/dokan/dokan_java/Unsigned.java:189]: Please add some explaining JavaDoc. The following questions should be answered:

1. What does this annotation mean.
1. Why is this annotation needed.
1. Are there pitfalls (e.g. division of unsigned numbers)

File: MAPPING.md [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+| unsigned long (int) | ULONG                     | 4B/32b            | int (@Unsigned)/WinDef.ULONG      |
+| unsigned long (int) | DWORD/AccessMask          | 4B/32b            | int (@Unsigned)/WinDef.DWORD      |
+| unsigned __int64    | ULONG64                   | 8B/64b            | long (@Unsigned)/WinDef.ULONGLONG |
+# References
+Basic Types/Size: [Web](https://docs.microsoft.com/en-us/cpp/c-language/storage-of-basic-types?view=vs-2019) | [Permalink](https://web.archive.org/web/20200616151823/https://docs.microsoft.com/en-us/cpp/c-language/storage-of-basic-types?view=vs-2019) <br>
+Windows Data Types/Mapped C Data Types: [Web](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types) | [Permalink](https://web.archive.org/web/20200616152122/https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types) <br>
+JNA Data Types: [Web](https://java-native-access.github.io/jna/5.5.0/javadoc/com/sun/jna/platform/win32/WinDef.html) | [Permalink](https://web.archive.org/web/20200616212719/https://java-native-access.github.io/jna/5.5.0/javadoc/com/sun/jna/platform/win32/WinDef.html) <br>
```
Comment (infeo) [inline MAPPING.md:12]: Imho not our responsiblilty to document this, because this is only interesting for developers of this library. But since the primary source is linked, it can stay.

**Review by infeo — CHANGES_REQUESTED** [review]
Generally I approve, but the (already previously) discussed changes need to be implemented.

File: src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java (hunk 1 above)
Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java:97]: Objection: In my opinion the example filesystem is the best place to teach usage of the annotation.

File: src/main/java/dev/dokan/dokan_java/structure/DokanControl.java (hunk 3 above)
Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/structure/DokanControl.java]: Resolved by commit 279b5b890b4b148a86fe25ad1d9b43f9fd7d8507

**Comment by JaniruTEC** [comment]
To document the reasoning for creating [MAPPING.md:](https://github.com/dokan-dev/dokan-java/blob/5895e92ead7046468f4dc4732cfb8c758d530089/MAPPING.md)
1. It's important to use the same mapping all over the project, therefore establishing a guideline seemed to be important.
2. It gives easy access to any sources regarding this matter.
3. It helps users of this API, as well as new developers (as well as old ones after a few weeks have passed) to understand the inner workings of the conversions between Dokany and dokan-java.

File: MAPPING.md (hunk 6 above)
Comment (JaniruTEC) [reply MAPPING.md:12]: See: https://github.com/dokan-dev/dokan-java/pull/48#issuecomment-647735932

File: src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java (hunk 1 above)
Comment (infeo) [reply src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java:97]: From my point of view the annotation is mostly to indicate how to treat a number given by or returned to the library. A developer using the filesystem can acknowledge it and handle it, but from the point in time where their code is executed it does not matter anymore, as long as they considered it when returning into the library again.

Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/examples/DirListingFileSystem.java:97]: In this case the sole purpose of the defined vars is to be returned to the filesystem. Therefore flagging them as "special" seems appropriate to me. The DirListingFileSystem should teach the correct way of using the dokan-java API and the best way to use it is to consistently keep track of unsigned values.

File: src/main/java/dev/dokan/dokan_java/UnsignedNumbers.java (hunk 4 above)
Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/UnsignedNumbers.java:25]: Resolved by commits 8a15e47 and 236347d

File: src/main/java/dev/dokan/dokan_java/structure/DokanControl.java [hunk 7]
```diff
@@ -73,25 +77,33 @@ public DokanControl(Pointer p, long offset) {
     }
 
     /**
-     * Creates a java {@link List} of {@link DokanControl} strcutures given the pointer returned by NativeMethods#DokanGetMountPointList(boolean, LongByReference).
+     * Creates a java {@link List} of {@link DokanControl} strcutures given the pointer returned by NativeMethods#DokanGetMountPointList(boolean, LongByReference).<br>
```
Comment (infeo) [inline src/main/java/dev/dokan/dokan_java/structure/DokanControl.java]: typo.

**Review by infeo — DISMISSED** [review]
Add the Javadoc for the annotation and this PR is ready to be merged.

File: src/main/java/dev/dokan/dokan_java/structure/DokanControl.java (hunk 7 above)
Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/structure/DokanControl.java]: Resolved by commit 75e582c

File: src/main/java/dev/dokan/dokan_java/Unsigned.java (hunk 5 above)
Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/Unsigned.java:189]: Revolved by commit b9aa49a902581c5ad01f01aeed07096d889973b0

File: src/main/java/dev/dokan/dokan_java/Unsigned.java [hunk 8]
```diff
@@ -10,6 +10,182 @@
...
+ * <h1>Usage</h1>
+ * As Java only supports signed numbers, the correct interpretation and handling of unsigned numbers must be dealt with by the developer.
+ * Because of this it's <b>strongly recommended</b> to tag all values that are unsigned as such <b>by using this annotation.</b><br>
+ * <i>@Unsigned</i> is defined to {@link Target target} {@link java.lang.annotation.ElementType#TYPE_PARAMETER} and
+ * {@link java.lang.annotation.ElementType#TYPE_USE} and can therefore be applied to all usages of types (type contexts)
+ * and parameterized types respectively. See <a href="https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.6.4.1">&sect9.6.4.1</a>
+ * and <a href="https://docs.oracle.com/javase/specs/jls/se11/html/jls-4.html#jls-4.11">&sect4.11</a> of "The Java&reg Language Specification" for
+ * further reference.<br>
+ * <br>
+ * At least the following cases ("minimum usage") should be annotated with <i>@Unsigned</i> to
```
Comment (JaniruTEC) [inline src/main/java/dev/dokan/dokan_java/Unsigned.java:79]: In the future it may be useful to check our/foreign source code for compliance to this rule, e.g. with [the Checker Framework.](https://github.com/typetools/checker-framework)

Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/Unsigned.java:79]: // Do not close this conversation //

File: src/main/java/dev/dokan/dokan_java/Unsigned.java [hunk 9]
```diff
@@ -0,0 +1,196 @@
...
+ * guarantee the best quality of code:
```
Comment (JaniruTEC) [inline src/main/java/dev/dokan/dokan_java/Unsigned.java:80]: In the future it may be useful to check our/foreign source code for compliance to this rule, e.g. with [the Checker Framework.](https://github.com/typetools/checker-framework)

Comment (JaniruTEC) [reply src/main/java/dev/dokan/dokan_java/Unsigned.java:80]: // Do not resolve or close. //
